// src/components/EventCard.vue
<template>
  <div class="card bg-surface-card rounded-md w-[250px]">
    <div class="relative flex flex-col border border-border-base h-full">
      <!-- upcoming icon -->
      <div
        v-if="isUpcoming"
        class="absolute -top-5 right-0 bg-cyan-600/60 border-2 border-cyan-700 text-white p-4 rounded-full text-lg"
      >
        <MdSharpUpcoming />
      </div>

      <img
        :src="image || 'https://placehold.co/300x120'"
        alt=""
        class="w-full h-50 object-cover"
      />

      <div class="flex flex-col px-4 py-3">
        <h2 class="text-md md:text-lg font-semibold">{{ title }}</h2>
        <p class="text-sm line-clamp-2">
          {{ description }}
        </p>
        <small class="text-text-muted">{{ date }}</small>

        <!-- <button class="w-fit self-end">
          <BsArrowReturnRight />
        </button> -->
      </div>
    </div>
  </div>
</template>

<script>
import { BsArrowReturnRight } from "@kalimahapps/vue-icons";
import { MdSharpUpcoming } from "@kalimahapps/vue-icons";
export default {
  props: ["image", "title", "description", "date", "isUpcoming"],
  components: {
    BsArrowReturnRight,
    MdSharpUpcoming,
  },
};
</script>

// src/lib/components/EventCard.svelte
<script lang="ts">
  import { Sparkle, CalendarBlank } from "phosphor-svelte";

  let {
    image,
    title,
    description,
    date,
    isUpcoming = false,
    tilt = "0deg",
  }: {
    image?: string;
    title?: string;
    description?: string;
    date?: string;
    isUpcoming?: boolean;
    tilt?: string;
  } = $props();
</script>

<article
  class="card group flex h-full flex-col overflow-hidden transition-[rotate] duration-200 hover:rotate-0"
  style="rotate: {tilt};"
>
  <div class="relative">
    <img
      src={image || "https://placehold.co/300x200"}
      alt={title ?? ""}
      class="h-44 w-full border-b-[2.5px] border-ink object-cover"
    />

    {#if isUpcoming}
      <span class="badge-up absolute -top-3 right-3">
        <Sparkle weight="fill" /> Upcoming
      </span>
    {/if}

    <span
      class="absolute bottom-3 left-3 inline-flex items-center gap-1.5 rounded-full border-2 border-ink bg-paper-2 px-2.5 py-1 text-xs font-bold shadow-[2px_2px_0_var(--color-ink)]"
    >
      <CalendarBlank weight="bold" class="text-gold-deep" />
      {date}
    </span>
  </div>

  <div class="flex flex-1 flex-col gap-2 p-5">
    <h3 class="text-2xl text-ink">{title}</h3>
    <p class="text-sm leading-relaxed text-ink-soft line-clamp-3">
      {description}
    </p>
  </div>
</article>
