// src/components/Footer.vue
<template>
  <footer class="bg-primary/90 border-t-2 border-border-base py-12">
    <div
      class="max-w-5xl mx-auto px-6 py-12 grid grid-cols-1 md:grid-cols-3 gap-10"
    >
      <!-- Logo & Tagline -->
      <div class="flex items-center gap-4 duration-70 ease-in">
        <h2 href="#" class="text-2xl font-extrabold md:text-3xl">
          Kagay-an Furs
        </h2>
        <FlColorAnimalPawPrint class="text-4xl rotate-45" />
      </div>

      <!-- Quick Links -->
      <div class="flex flex-col gap-3">
        <p class="text-xs font-bold uppercase text-text-main">Quick Links</p>
        <a
          href="#home"
          class="text-sm text-white/80 hover:text-white transition-colors"
          >Home</a
        >
        <a
          href="#events"
          class="text-sm text-white/80 hover:text-white transition-colors"
          >Events</a
        >
        <a
          href="#about"
          class="text-sm text-white/80 hover:text-white transition-colors"
          >About</a
        >
      </div>

      <!-- Socials -->
      <div class="flex flex-col gap-3">
        <p class="text-xs font-bold uppercase text-text-main">Find Us</p>

        <a
          :href="socialLinks.facebook"
          target="_blank"
          class="flex items-center gap-2 text-sm text-white/80 hover:text-white transition-colors"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="w-4 h-4"
            viewBox="0 0 24 24"
            fill="currentColor"
          >
            <path
              d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"
            />
          </svg>
          Facebook
        </a>

        <a
          :href="socialLinks.discord"
          target="_blank"
          class="flex items-center gap-2 text-sm text-white/80 hover:text-white transition-colors"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="w-4 h-4"
            viewBox="0 0 24 24"
            fill="currentColor"
          >
            <path
              d="M20.317 4.37a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.21.375-.444.864-.608 1.25a18.27 18.27 0 0 0-5.487 0 12.64 12.64 0 0 0-.617-1.25.077.077 0 0 0-.079-.037A19.736 19.736 0 0 0 3.677 4.37a.07.07 0 0 0-.032.027C.533 9.046-.32 13.58.099 18.057c.002.022.015.043.03.056a19.9 19.9 0 0 0 5.993 3.03.078.078 0 0 0 .084-.028 14.09 14.09 0 0 0 1.226-1.994.076.076 0 0 0-.041-.106 13.107 13.107 0 0 1-1.872-.892.077.077 0 0 1-.008-.128 10.2 10.2 0 0 0 .372-.292.074.074 0 0 1 .077-.01c3.928 1.793 8.18 1.793 12.062 0a.074.074 0 0 1 .078.01c.12.098.246.198.373.292a.077.077 0 0 1-.006.127 12.299 12.299 0 0 1-1.873.892.077.077 0 0 0-.041.107c.36.698.772 1.362 1.225 1.993a.076.076 0 0 0 .084.028 19.839 19.839 0 0 0 6.002-3.03.077.077 0 0 0 .032-.054c.5-5.177-.838-9.674-3.549-13.66a.061.061 0 0 0-.031-.03zM8.02 15.33c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.956-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.956 2.418-2.157 2.418zm7.975 0c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.955-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.946 2.418-2.157 2.418z"
            />
          </svg>
          Discord
        </a>

        <a
          :href="socialLinks.github"
          target="_blank"
          class="flex items-center gap-2 text-sm text-white/80 hover:text-white transition-colors"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="w-4 h-4"
            viewBox="0 0 24 24"
            fill="currentColor"
          >
            <path
              d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"
            />
          </svg>
          GitHub
        </a>

        <a
          :href="socialLinks.furriesph"
          target="_blank"
          class="text-sm text-white/80 hover:text-white transition-colors"
        >
          furries.ph
        </a>
      </div>
    </div>

    <!-- Bottom Bar -->
    <div class="border-t border-white/20 py-4">
      <p class="text-center text-sm text-white">
        © {{ new Date().getFullYear() }} KFM. All rights reserved.
      </p>
    </div>
  </footer>
</template>

<script>
import { FlColorAnimalPawPrint } from "@kalimahapps/vue-icons";
import { socialLinks } from "../constants";

export default {
  components: {
    FlColorAnimalPawPrint,
  },
  data() {
    return {
      socialLinks,
    };
  },
};
</script>

// src/lib/components/Footer.svelte
<script lang="ts">
  import {
    PawPrint,
    FacebookLogo,
    DiscordLogo,
    GithubLogo,
    ArrowUpRight,
  } from "phosphor-svelte";
  import { socialLinks } from "$lib/constants";

  const year = new Date().getFullYear();

  const socials = [
    { label: "Facebook", href: socialLinks.facebook, Icon: FacebookLogo },
    { label: "Discord", href: socialLinks.discord, Icon: DiscordLogo },
    { label: "GitHub", href: socialLinks.github, Icon: GithubLogo },
    { label: "furries.ph", href: socialLinks.furriesph, Icon: PawPrint },
  ];
</script>

<footer class="relative mt-24 bg-ink text-paper">
  <div class="mx-auto max-w-6xl px-5 py-16 md:px-12">
    <div class="grid grid-cols-1 gap-12 md:grid-cols-[1.4fr_1fr_1fr]">
      <!-- brand -->
      <div>
        <div class="flex items-center gap-3">
          <span
            class="grid h-11 w-11 place-items-center rounded-full border-[2.5px] border-paper bg-gold"
          >
            <PawPrint weight="fill" class="text-2xl text-ink" />
          </span>
          <span class="font-display text-3xl font-black tracking-tight">
            Kagay-an Furs
          </span>
        </div>
        <p class="mt-5 max-w-sm text-paper/70">
          The first &amp; only furry meetup community in Cagayan de Oro.
          Paws up, tails out, everyone's welcome.
        </p>
      </div>

      <!-- quick links -->
      <div class="flex flex-col gap-3">
        <p class="eyebrow text-gold">Explore</p>
        <a href="/" class="footer-link">Home</a>
        <a href="/#events" class="footer-link">Events</a>
        <a href="/#about" class="footer-link">About</a>
        <a href="/team" class="footer-link">Team</a>
        <a href="/code-of-conduct" class="footer-link">Code of Conduct</a>
      </div>

      <!-- socials -->
      <div class="flex flex-col gap-3">
        <p class="eyebrow text-gold">Find us</p>
        {#each socials as s (s.label)}
          <a
            href={s.href}
            target="_blank"
            class="footer-link group inline-flex items-center gap-2"
          >
            <s.Icon weight="fill" class="text-lg" />
            {s.label}
            <ArrowUpRight
              weight="bold"
              class="text-sm opacity-0 transition-opacity group-hover:opacity-100"
            />
          </a>
        {/each}
      </div>
    </div>

    <div
      class="mt-14 flex flex-col items-center justify-between gap-4 border-t border-paper/20 pt-6 sm:flex-row"
    >
      <p class="text-sm text-paper/60">
        © {year} Kagay-an Furs · KFM. All rights reserved.
      </p>
      <div class="flex items-center gap-1.5 text-gold">
        <PawPrint weight="fill" />
        <PawPrint weight="fill" />
        <PawPrint weight="fill" />
      </div>
    </div>
  </div>
</footer>

<style>
  .footer-link {
    color: color-mix(in srgb, var(--color-paper) 78%, transparent);
    font-weight: 500;
    width: fit-content;
    transition: color 0.15s ease;
  }
  .footer-link:hover {
    color: var(--color-gold);
  }
</style>
